name: LGD-env

channels:
  - conda-forge

dependencies:
  - python=3.7
  - numpy=1.16.3
  - pandas=0.24.2
  - matplotlib=3.0.3
  - scikit-learn=0.21.3
  - seaborn=0.9.0
  - pip
  - pip:
    - integrate
    - datetime